apiVersion: v1
data:
  nginx.conf: |-
    events {
        worker_connections 1024;
    }
    http {
        server {
           listen 80;
           server_name myserver;

           location / {
               proxy_pass http://myapp:80;
               proxy_set_header Host $host;
               proxy_set_header X-Real-IP $remote_addr;
               proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
               auth_basic "Restricted Content";
               auth_basic_user_file /etc/nginx/.htpasswd;
           }
        }
    }
kind: ConfigMap
metadata:
  name: my-nginx-config
